server:
  port: 8082

spring:
  application:
    name: pos-api

  cache:
    type: redis

  data:
    redis:
      host: ${API_POS_REDIS_HOST}
      port: ${API_POS_REDIS_PORT}
      password: ${API_POS_REDIS_PASSWORD}
      database: ${API_POS_REDIS_DB}

  datasource:
    url: jdbc:postgresql://${API_POS_DATABASE_HOST}:${API_POS_DATABASE_PORT}/${API_POS_DATABASE_DB}?currentSchema=${API_POS_DATABASE_SCHEMA}
    username: ${API_POS_DATABASE_USERNAME}
    password: ${API_POS_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${API_POS_RABBITMQ_HOST:localhost}
    port: ${API_POS_RABBITMQ_PORT:5672}
    username: ${API_POS_RABBITMQ_USERNAME:guest}
    password: ${API_POS_RABBITMQ_PASSWORD:guest}
    exchanges:
      sales: sales-exchange
      inventory: inventory-exchange
      payments: payments-exchange
    routing-keys:
      sale-started: sale.started
      sale-completed: sale.completed
      sale-failed: sale.failed
      inventory:
        reserve: inventory.reserve
        product: inventory.product.request
      payments:
        started: payments.payment.started
        update: payments.payment.update
