server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ms-email
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  mail:
    host: smtp.gmail.com
    port: 587
    username: lhchoinski04@gmail.com
    password: akkh zqic srdi vvzu

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

broker:
  queue:
    email:
      name: default.email
