apiVersion: v1
kind: Service
metadata:
  name: sales-api
  labels:
    app: sales-api
spec:
  selector:
    app: sales-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP
