server:
  port: 8081

spring:
  application:
    name: estoque

  cache:
    type: redis

  data:
    redis:
      host: ${API_ESTOQUE_REDIS_HOST}
      port: ${API_ESTOQUE_REDIS_PORT}
      password: ${API_ESTOQUE_REDIS_PASSWORD}
      database: ${API_ESTOQUE_REDIS_DB}

  datasource:
    url: jdbc:postgresql://${API_ESTOQUE_DATABASE_HOST}:${API_ESTOQUE_DATABASE_PORT}/${API_ESTOQUE_DATABASE_DB}?currentSchema=${API_ESTOQUE_DATABASE_SCHEMA}
    username: ${API_ESTOQUE_DATABASE_USERNAME}
    password: ${API_ESTOQUE_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  liquibase:
      enabled: true
      drop-first: false
      change-log: classpath:db/changelog/db.changelog-master-inventory.xml
      default-schema: public

  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: none

  rabbitmq:
    host: ${API_ESTOQUE_RABBITMQ_HOST}
    port: ${API_ESTOQUE_RABBITMQ_PORT}
    username: ${API_ESTOQUE_RABBITMQ_USERNAME}
    password: ${API_ESTOQUE_RABBITMQ_PASSWORD}
    exchanges:
      sales: sales-exchange
      inventory: inventory-exchange
      payments: payment
    routing-keys:
      sale-started: sale.started
      sale-completed: sale.completed
      sale-failed: sale.failed
      inventory:
        reserve: inventory.product.reserve
        product: inventory.product.request
      payments:
        started: payments.payment.started
